# Equations

- 3 weight matrices

\begin{align}
h_t &= f_W(h_{t-1}, x_t) \\
h_t &= \tanh(W_{hh}h_{t-1}+W_{xh}x_t) \\
y_t &= W_{hy}h_t
\end{align}

# Types of RNN

![](imgs/types_of_rnn.png)

- one-to-one: vanilla
- one-to-many: image caption
- many-to-one: sentiment analysis
- many-to-many-1: machine translation
- many-to-many-2: video classification on frame level

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
chars = ['h','e','l','o']
x_data = np.array([[1,0,0,0],
                   [0,1,0,0],
                   [0,0,1,0],
                   [0,0,1,0]], dtype='f')    # hell
y_data = [1,2,2,3]    # ello
print x_data

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  1.  0.]]


In [3]:
# hyper-params
rnn_size = len(chars)
time_step_size = 4
batch_size = 1

In [4]:
# model
rnn_cell = tf.nn.rnn_cell.BasicRNNCell(rnn_size)
state = tf.zeros([batch_size, rnn_cell.state_size])   # h_0
x_split = tf.split(0, time_step_size, x_data)
outputs, state = tf.nn.rnn(rnn_cell, x_split, state)

In [5]:
# loss
logits = tf.reshape(tf.concat(1, outputs), [-1, rnn_size])    # y'
targets = tf.reshape(y_data, [-1])                            # y
weights = tf.ones([time_step_size * batch_size])
loss = tf.nn.seq2seq.sequence_loss_by_example([logits], [targets], [weights])
cost = tf.reduce_sum(loss) / batch_size
train = tf.train.RMSPropOptimizer(0.01, 0.9).minimize(cost)

In [6]:
# train
with tf.Session() as sess:
    tf.initialize_all_variables().run()
    for i in range(100):
        sess.run(train)
        result = sess.run(tf.argmax(logits, 1))
        print result, [chars[t] for t in result]

[3 1 0 0] ['o', 'e', 'h', 'h']
[3 1 0 0] ['o', 'e', 'h', 'h']
[3 1 0 0] ['o', 'e', 'h', 'h']
[3 1 0 0] ['o', 'e', 'h', 'h']
[3 1 0 0] ['o', 'e', 'h', 'h']
[3 1 0 0] ['o', 'e', 'h', 'h']
[3 3 0 0] ['o', 'o', 'h', 'h']
[3 3 0 0] ['o', 'o', 'h', 'h']
[3 3 0 0] ['o', 'o', 'h', 'h']
[3 3 0 0] ['o', 'o', 'h', 'h']
[3 2 0 0] ['o', 'l', 'h', 'h']
[3 2 0 0] ['o', 'l', 'h', 'h']
[3 2 2 0] ['o', 'l', 'l', 'h']
[3 2 2 0] ['o', 'l', 'l', 'h']
[3 2 2 0] ['o', 'l', 'l', 'h']
[3 2 2 0] ['o', 'l', 'l', 'h']
[3 2 2 0] ['o', 'l', 'l', 'h']
[3 2 2 0] ['o', 'l', 'l', 'h']
[3 2 2 0] ['o', 'l', 'l', 'h']
[3 2 2 0] ['o', 'l', 'l', 'h']
[3 2 2 0] ['o', 'l', 'l', 'h']
[3 2 2 0] ['o', 'l', 'l', 'h']
[3 2 2 0] ['o', 'l', 'l', 'h']
[3 2 2 2] ['o', 'l', 'l', 'l']
[3 2 2 2] ['o', 'l', 'l', 'l']
[3 2 2 2] ['o', 'l', 'l', 'l']
[3 2 2 2] ['o', 'l', 'l', 'l']
[3 2 2 2] ['o', 'l', 'l', 'l']
[3 2 2 2] ['o', 'l', 'l', 'l']
[3 2 2 2] ['o', 'l', 'l', 'l']
[3 2 2 2] ['o', 'l', 'l', 'l']
[1 2 2 2] ['e', 'l', 'l', 'l']
[1 2 2 2